-- Identity DB

-- DROP INDEXES --
DROP INDEX IF EXISTS IDX_CON_APP_KEY;
DROP INDEX IF EXISTS IDN_OPENID_REMEMBER_ME_LOWER_USER_NAME_TENANT_ID;
DROP INDEX IF EXISTS IDN_OPENID_USER_RPS_LOWER_USER_NAME_TENANT_ID_RP_URL;
DROP INDEX IF EXISTS IDN_IDENTITY_USER_DATA_TENANT_ID_LOWER_USER_NAME_DATA_KEY;
DROP INDEX IF EXISTS IDN_IDENTITY_META_DATA_TENANT_ID_LOWER_USER_NAME_METADATA_TYPE_METADATA;
DROP INDEX IF EXISTS IDN_AUTH_USER_LOWER_USER_NAME_TENANT_ID_DOMAIN_NAME_IDP_ID;
DROP INDEX IF EXISTS IDN_USER_ACCOUNT_ASSOCIATION_TENANT_ID_DOMAIN_NAME_LOWER_USER_NAME;
DROP INDEX IF EXISTS FIDO_DEVICE_STORE_TENANT_ID_DOMAIN_NAME_LOWER_USER_NAME_KEY_HANDLE;
DROP INDEX IF EXISTS IDN_RECOVERY_DATA_LOWER_USER_NAME_USER_DOMAIN_TENANT_ID_SCENARIO_STEP;
DROP INDEX IF EXISTS IDN_PASSWORD_HISTORY_DATA_LOWER_USER_NAME_USER_DOMAIN_TENANT_ID_SALT_VALUE_HASH;
DROP INDEX IF EXISTS IDX_AT_TI_UD;
DROP INDEX IF EXISTS IDX_AT_CKID_AU_TID_UD_TSH_TS;
DROP INDEX IF EXISTS IDX_AT_CK_AU_LO;
DROP INDEX IF EXISTS IDX_AT_AU_TID_UD_TS_CKID_LO;
DROP INDEX IF EXISTS IDX_AT_AU_CKID_TS_UT_LO;
DROP INDEX IF EXISTS IDX_AUTHORIZATION_CODE_AU_TI;
DROP INDEX IF EXISTS IDX_LOWER_AUTH_USER_UN_TID_DN;
DROP INDEX IF EXISTS IDX_AUTH_SAI_UN_AID_SID;
DROP INDEX IF EXISTS IDX_OCA_UM_TID_UD_APN;
DROP INDEX IF EXISTS IDX_FIDO2_STR;
DROP INDEX IF EXISTS IDX_AI_DN_LO_UN_AI;
DROP INDEX IF EXISTS IDX_SP_APP_NAME_CI;
DROP INDEX IF EXISTS idn_auth_user_user_name_tenant_id_domain_name_idp_id;


-- CREATE INDEXES --


CREATE UNIQUE INDEX IDX_CON_APP_KEY ON IDN_OAUTH2_ACCESS_TOKEN(CONSUMER_KEY_ID, AUTHZ_USER, TENANT_ID,
            USER_DOMAIN, USER_TYPE, TOKEN_SCOPE_HASH, TOKEN_STATE, TOKEN_STATE_ID, IDP_ID, TOKEN_BINDING_REF,
            AUTHORIZED_ORGANIZATION);

CREATE UNIQUE INDEX IDN_OPENID_REMEMBER_ME_USER_NAME_TENANT_ID ON IDN_OPENID_REMEMBER_ME(USER_NAME, TENANT_ID);

CREATE UNIQUE INDEX IDN_OPENID_USER_RPS_USER_NAME_TENANT_ID_RP_URL ON IDN_OPENID_USER_RPS(USER_NAME, TENANT_ID, RP_URL);

CREATE UNIQUE INDEX IDN_IDENTITY_USER_DATA_TENANT_ID_USER_NAME_DATA_KEY ON IDN_IDENTITY_USER_DATA(TENANT_ID, USER_NAME, DATA_KEY);

CREATE UNIQUE INDEX IDN_IDENTITY_META_DATA_TENANT_ID_USER_NAME_METADATA_TYPE_METADATA ON IDN_IDENTITY_META_DATA(TENANT_ID, USER_NAME, METADATA_TYPE, METADATA);

CREATE UNIQUE INDEX IDN_AUTH_USER_USER_NAME_TENANT_ID_DOMAIN_NAME_IDP_ID ON IDN_AUTH_USER(USER_NAME, TENANT_ID, DOMAIN_NAME, IDP_ID);

CREATE UNIQUE INDEX IDN_USER_ACCOUNT_ASSOCIATION_TENANT_ID_DOMAIN_NAME_USER_NAME ON IDN_USER_ACCOUNT_ASSOCIATION(TENANT_ID, DOMAIN_NAME, USER_NAME);

CREATE UNIQUE INDEX FIDO_DEVICE_STORE_TENANT_ID_DOMAIN_NAME_USER_NAME_KEY_HANDLE ON FIDO_DEVICE_STORE(TENANT_ID, DOMAIN_NAME, USER_NAME, KEY_HANDLE);

CREATE UNIQUE INDEX IDN_RECOVERY_DATA_USER_NAME_USER_DOMAIN_TENANT_ID_SCENARIO_STEP ON IDN_RECOVERY_DATA(USER_NAME, USER_DOMAIN, TENANT_ID, SCENARIO, STEP);

CREATE UNIQUE INDEX IDN_PASSWORD_HISTORY_DATA_USER_NAME_USER_DOMAIN_TENANT_ID_SALT_VALUE_HASH ON IDN_PASSWORD_HISTORY_DATA(USER_NAME, USER_DOMAIN, TENANT_ID, SALT_VALUE, HASH);

CREATE INDEX IDX_AT_TI_UD ON IDN_OAUTH2_ACCESS_TOKEN(AUTHZ_USER, TENANT_ID, TOKEN_STATE, USER_DOMAIN);

CREATE INDEX IDX_AT_CKID_AU_TID_UD_TSH_TS ON IDN_OAUTH2_ACCESS_TOKEN(CONSUMER_KEY_ID, AUTHZ_USER, TENANT_ID, USER_DOMAIN, TOKEN_SCOPE_HASH, TOKEN_STATE);
CREATE INDEX IDX_AT_CK_AU_LO ON IDN_OAUTH2_ACCESS_TOKEN(CONSUMER_KEY_ID, AUTHZ_USER, TOKEN_STATE, USER_TYPE);
CREATE INDEX IDX_AT_AU_TID_UD_TS_CKID_LO ON IDN_OAUTH2_ACCESS_TOKEN(AUTHZ_USER, TENANT_ID, USER_DOMAIN, TOKEN_STATE, CONSUMER_KEY_ID);
CREATE INDEX IDX_AT_AU_CKID_TS_UT_LO ON IDN_OAUTH2_ACCESS_TOKEN(AUTHZ_USER, CONSUMER_KEY_ID, TOKEN_STATE, USER_TYPE);

CREATE INDEX IDX_AUTHORIZATION_CODE_AU_TI ON IDN_OAUTH2_AUTHORIZATION_CODE (AUTHZ_USER, TENANT_ID, USER_DOMAIN, STATE);

CREATE INDEX IDX_AUTH_USER_UN_TID_DN ON IDN_AUTH_USER (USER_NAME, TENANT_ID, DOMAIN_NAME);

CREATE INDEX IDX_AUTH_SAI_UN_AID_SID ON IDN_AUTH_SESSION_APP_INFO (APP_ID, SUBJECT, SESSION_ID);

CREATE INDEX IDX_OCA_UM_TID_UD_APN ON IDN_OAUTH_CONSUMER_APPS(USERNAME,TENANT_ID,USER_DOMAIN, APP_NAME);

CREATE INDEX IDX_FIDO2_STR ON FIDO2_DEVICE_STORE(USER_NAME, TENANT_ID, DOMAIN_NAME, CREDENTIAL_ID, USER_HANDLE);

CREATE INDEX IDX_AI_DN_LO_UN_AI ON IDN_ASSOCIATED_ID(DOMAIN_NAME, USER_NAME, ASSOCIATION_ID);

CREATE INDEX IDX_SP_APP_NAME_CI ON SP_APP (APP_NAME);
