-- Shared DB


-- Drop indexes from UM_USER
DROP INDEX IF EXISTS INDEX_LOWER_UM_USER_NAME_UM_TENANT_ID;
DROP INDEX IF EXISTS IDX_UU_LO_UI_UUN_TI;

-- Drop index from UM_SYSTEM_USER
DROP INDEX IF EXISTS UM_SYSTEM_USER_LOWER_UM_USER_NAME_UM_TENANT_ID;

-- Drop index from UM_USER_PERMISSION
DROP INDEX IF EXISTS UM_USER_PERMISSION_UM_PERMISSION_ID_LOWER_UM_USER_NAME_UM_TENANT_ID;

-- Drop index from UM_ACCOUNT_MAPPING
DROP INDEX IF EXISTS UM_ACCOUNT_MAPPING_LOWER_UM_USER_NAME_UM_TENANT_ID_UM_USER_STORE_DOMAIN_UM_ACC_LINK_ID;

-- Drop index from UM_HYBRID_USER_ROLE
DROP INDEX IF EXISTS UM_HYBRID_USER_ROLE_LOWER_UM_USER_NAME_UM_ROLE_ID_UM_TENANT_ID_UM_DOMAIN_ID;

-- Drop index from UM_SYSTEM_USER_ROLE
DROP INDEX IF EXISTS UM_SYSTEM_USER_ROLE_LOWER_UM_USER_NAME_UM_ROLE_ID_UM_TENANT_ID;


-- Recreate indexes for UM_USER, UM_SYSTEM_USER, UM_USER_PERMISSION, UM_ACCOUNT_MAPPING, UM_HYBRID_USER_ROLE, and UM_SYSTEM_USER_ROLE


CREATE INDEX IDX_UU_UI_UUN_TI ON UM_USER(UM_ID, UM_USER_NAME, UM_TENANT_ID);

CREATE UNIQUE INDEX UM_SYSTEM_USER_UM_USER_NAME_UM_TENANT_ID ON UM_SYSTEM_USER(UM_USER_NAME, UM_TENANT_ID);

CREATE INDEX UM_USER_PERMISSION_UM_PERMISSION_ID_UM_USER_NAME_UM_TENANT_ID ON
            UM_USER_PERMISSION(UM_PERMISSION_ID, UM_USER_NAME, UM_TENANT_ID);

CREATE UNIQUE INDEX UM_ACCOUNT_MAPPING_UM_USER_NAME_UM_TENANT_ID_UM_USER_STORE_DOMAIN_UM_ACC_LINK_ID ON UM_ACCOUNT_MAPPING(UM_USER_NAME, UM_TENANT_ID, UM_USER_STORE_DOMAIN, UM_ACC_LINK_ID);

CREATE UNIQUE INDEX UM_HYBRID_USER_ROLE_UM_USER_NAME_UM_ROLE_ID_UM_TENANT_ID_UM_DOMAIN_ID ON UM_HYBRID_USER_ROLE(UM_USER_NAME, UM_ROLE_ID, UM_TENANT_ID, UM_DOMAIN_ID);

CREATE UNIQUE INDEX UM_SYSTEM_USER_ROLE_UM_USER_NAME_UM_ROLE_ID_UM_TENANT_ID ON UM_SYSTEM_USER_ROLE(UM_USER_NAME, UM_ROLE_ID, UM_TENANT_ID);


-- Identity DB


