apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-slave
spec:
  replicas: {{ .Values.slave.replicaCount }}
  selector:
    matchLabels:
      app: jmeter-slave
  template:
    metadata:
      labels:
        app: jmeter-slave
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: jmeter-slave
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["jmeter-server"]
          ports:
            - containerPort: 1099
            - containerPort: 50000
          env:
            - name: JVM_ARGS
              value: "-Djava.rmi.server.hostname=$(POD_IP)"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
